### ISSUE TITLE
num_ref_pcd

### ISSUE THREAD

**Issue by Crane-YU** [canonical-capsules/canonical-capsules#12]
Hi @wsunid,

Thanks for your great work. While I was reading your code, I got confused by the argument "self.num_ref_pcd".
Coud u plz explain why you use it and why is it set to 1.
Thank you.

**Comment by wsunid** [comment]
Hi, this is for one of the ablation experiments where we show the results of one-shot learning (probably in our supplementary). Basically the `self.num_ref_pcd` means the number of shots.

**Comment by Crane-YU** [comment]
Thank you.
