### ISSUE TITLE
Classification Feature Specification

### ISSUE THREAD

**Issue by curiosity654** [canonical-capsules/canonical-capsules#2]
Hi there, thanks for the amazing work. I have a question about the classification script. save_feat in `network.py` is in test mode, but in forward_test, the model only returns acc and an empty feature dict, could you please provide the components of the feature you used in classification?
![image](https://user-images.githubusercontent.com/34833233/108794088-1f0c4300-75c0-11eb-8b64-be2ae6a59b6c.png)
![image](https://user-images.githubusercontent.com/34833233/108794143-3b0fe480-75c0-11eb-845c-92a6d5684cd5.png)

**Comment by curiosity654** [comment]
Specifically, I just want to ensure if the classification is done with the concatenation of per capsule descriptor and regressed pose.

**Comment by wsunid** [comment]
Hi, thanks for your interest in our work! Yes, we generate the final feature fed to the classifier by flattening multiple capsules (with the concatenation of pose and descriptor).  

You could customize the returned feature dict. I removed the feature dict for brevity. Actually, you could also have a look at our [classification pipeline](https://github.com/canonical-capsules/canonical-capsules/blob/9cf7df83b93c8bc974d96077411c93e40e7ef702/classification.py#L53). It shows how we customized the returned feature dict and used capsules in classifications.

**Comment by curiosity654** [comment]
Thank you for the quick response, now I've reproduced the results in the paper😃.

**Comment by toobaimt** [comment]
Hi, so in terms of code, the final feature is gc? (
<img width="489" alt="Screen Shot 2021-05-10 at 4 36 20 PM" src="https://user-images.githubusercontent.com/11949455/117653453-dcfda100-b1ad-11eb-9f95-a7f8ff04d0a5.png">
)
