### ISSUE TITLE
ShapeNet Dataset Preparation

### ISSUE THREAD

**Issue by ArthLeu** [canonical-capsules/canonical-capsules#3]
data_utils/ShapeNetLoader.py has many paths that are hard to understand. 

What is 
data_dump/ , 
data_dump/ShapeNet, 
data_dump/ShapeNet/customShapeNet
data_dump/ShapeNet/ShapeNet
data_dump/ShapeNet/ShapeNet/ShapNetRendering (no longer available with the link in AtlasNetV2 README.md)
./data/ShapeNetCorev2
etc. ?

Could you post a correct folder map so that ShapeNetLoader.py can run successfully? Or a detail instruction on how to prepare the ShapeNet data downloaded with AtlasNetV2?

**Comment by wsunid** [comment]
Those data paths are copied from AtlasNetV2's [data loader ](https://github.com/TheoDEPRELLE/AtlasNetV2/blob/master/auxiliary/dataset.py). 

To generate data, I just run the AtlasNetV2's data loader and save the data into an h5 file. So please firstly follow AtlasNetV2's guide to prepare data and then run our script to load the data into the h5 file. 

If the link in AtlasNetV2 is invalid, one possible workaround is to download the data in ShapeNet.org. Or you could simply make your own data loader that feeds point clouds to the network if you have data around.

**Comment by wsunid** [comment]
Let me know if you have further questions. And of course, feel free to re-open this issue.

**Comment by pxing6** [comment]
I am reproducing your paper now,can you provide some ways to download shapnetV2,AtlasNetV2 data loader can not prepare the data now.can you find a link to download it.thanks.
