### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by StevenZzz07** [canonical-capsules/canonical-capsules#4]
Hi, first thanks for your inspiring work! Point cloud rendering figures in your paper are very beautiful as follows. How do you draw it? Using open3d, meshlab or other programmes?

Thanks!
![image](https://user-images.githubusercontent.com/56421441/110420372-1f373300-80d6-11eb-9bd6-272ec1febaf8.png)

**Comment by StevenZzz07** [comment]
Thank you very much! I will try it out right now!!

**Comment by wsunid** [comment]
Hi, feel free to re-open the issue if you need further help :))
