### ISSUE TITLE
a question about the operation of the source code

### ISSUE THREAD

**Issue by sycamore27** [canonical-capsules/canonical-capsules#5]
Hello, I'm a novice in deep learning, because there are no comments on the code and I don't have enough experience. I'd like to ask you some questions about the operation of the source code. When I tried to train 2D plane data set shapenet_plane_2d, I reported an error "filenotfounderror: [errno 2] no such file or directory: 'data_ dump/ShapeNetAtlasNetH5/train_ cat.txt '”。 But I don't see this folder in the cloned file.  I don't also know where to create the folder data_dump_folder. How can I modify it? Thank you very much!

**Comment by wsunid** [comment]
Hi, you could simply generate a file `train_cat.txt` in which you fill the class id you like to train with:

```
bench.h5
cabinet.h5
car.h5
cellphone.h5
chair.h5
couch.h5
firearm.h5
lamp.h5
monitor.h5
plane.h5
speaker.h5
table.h5
watercraft.h5
```

**Comment by wsunid** [comment]
Hi, feel free to reopen the issue if you need further help :))
