### ISSUE TITLE
random_T_100k_uni-180-0.2.h5 error message = No such directory 

### ISSUE THREAD

**Issue by amandeep25** [canonical-capsules/canonical-capsules#6]
I have been trying this code for my project but am encountering this error message "random_T_100k_uni-180-0.2.h5 error message = No such directory".
Kindly tell me the:
1. Significance of this file
2. Where to find/generate this file
@taiya @wsunid @Awcrr

**Comment by wsunid** [comment]
Hi, it's a file regarding the data. It's used to fix the randomness in evaluations. You could generate random transformation matrixes and save them in the 'h5' file.

Here is one related [issue discussion](https://github.com/canonical-capsules/canonical-capsules/issues/1#issuecomment-792761320) that might be helpful to you.

**Comment by djsamyak** [comment]
Would it be possible for you to share the "random_T_100k_uni-180-0.2.h5" file itself? If not, could you perhaps provide deeper insights into the number of matrices and their dimensions?

**Comment by wsunid** [comment]
Hi, this file is not essential to run the code. It's only used to fix the randomness in evaluation. In order to run the code without this file, you could simply disable the flag `freeze_data=False` when using the ShapeNet dataset loader.

About how to prepare this file, you could simply sample random poses and save them in an `h5` file named `random_T_100k_uni-180-0.2.h5`.

For example:
```
def random_pose_uni(N, range="uni-180-0"):
    limit_rot, limit_t = range.split("-")[1:]

    rots = random_rot((N, ), limit=float(limit_rot)) # N33
    ts = random_t((N, ), limit=float(limit_t)) # N31
    zeros_one = np.array([[[0, 0, 0, 1]]] * N) # N14

    transform = np.concatenate([np.concatenate([rots, ts], 2), zeros_one], 1)
    return transform
  
def generate_random_transformation():
    random_range = "uni-180-0.2"
    fn = f"random_T_100k_{random_range}.h5"
    transform = random_pose_uni(
        N=100000, range=random_range).astype("float32")
    with h5py.File(fn, "w") as f:
        f["transform"] =transform 
        
generate_random_transformation()
```
