### ISSUE TITLE
Misc confusions.

### ISSUE THREAD

**Issue by ZhaoyangZh** [canonical-capsules/canonical-capsules#8]
1. What is the definition of `self.ref_pcd`?
https://github.com/canonical-capsules/canonical-capsules/blob/fd4a69c19073ab63bb1511703386dcd9eed9e021/models/acne_ae.py#L145

I am not sure whether I had something wrong when interpreting the code. Appreciate your help, many thanks!

**Comment by wsunid** [comment]
Hi, 

This is for our additional few-shot learning experiments. Basically, instead of regressing the canonical pose via our keypoint regressor, in the few-shot learning setup, we provide the object in the canonical pose. Please refer to our supplementary (table 9) for more details.

-Weiwei.

**Comment by ZhaoyangZh** [comment]
Sure, thanks for your reply!
