### ISSUE TITLE
Question about aligner and shape completion of non-canonicalized object

### ISSUE THREAD

**Issue by darrenjkt** [canonical-capsules/canonical-capsules#9]
Hi, thanks for your work. It's a fantastic read. 

I have a question about the aligner. From the paper, I understand that there is a decomposition, canonicalisation and autoencoder part to the method. Where does the aligner fit within this framework? It seems to me that the aligner encompasses the decomposition and canonicalisation framework, am I right in assuming that? 

My goal is to try and use canonical capsules to complete the shape of incomplete lidar object scans that are not in a canonicalised pose. How can I adopt the configurations to do so? This was my result when I tried to feed a KITTI car into canonical capsules without normalizing to canonical pose.

![image](https://user-images.githubusercontent.com/39115809/155457491-84a3f1ad-4c1d-4a2b-aac8-79a4eb0563bb.png)

**Comment by wsunid** [comment]
Hi,

The aligner is actually the canonicalizer. Sorry for the confusing notation.

Regarding your results, I'm not very sure about what it means by your visualization. Does that look sadly bad?

And also, I guess here is another paper that is worth reading if you want to apply canonical capsues into incomplete shape.

Sajnani et al. ConDor: Self-Supervised Canonicalization of 3D Pose for Partial Shapes. 
https://arxiv.org/abs/2201.07788

Best,
Weiwei.

**Comment by darrenjkt** [comment]
Thanks for that paper link! After digging more into your paper/code I realised that your method wasn't specifically for the task I was trying to achieve and so you can ignore my visualization. 

If you have more paper links to this kind of work I would love to read them! The amount of work in shape completion of partial uncanonicalized shapes does seem quite sparse so I'll take any relevant work I can get haha

**Comment by wsunid** [comment]
Good luck! LOL
